2025-03-06 00:34:46,645 INFO    MainThread:1541937 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/kanchan/Downloads/Courses/DL(DA6401)/CS23S025-Assignment-1_DA6401-DL/wandb/run-20250306_003446-deir79f2/logs/debug.log
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/kanchan/Downloads/Courses/DL(DA6401)/CS23S025-Assignment-1_DA6401-DL/wandb/run-20250306_003446-deir79f2/logs/debug-internal.log
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7d10b9309ee0>
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:init():761] calling init triggers
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:init():784] starting backend
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [wandb_init.py:init():788] sending inform_init request
2025-03-06 00:34:46,646 INFO    MainThread:1541937 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-06 00:34:46,647 INFO    MainThread:1541937 [wandb_init.py:init():803] backend started and connected
2025-03-06 00:34:46,649 INFO    MainThread:1541937 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-06 00:34:46,649 INFO    MainThread:1541937 [wandb_init.py:init():896] updated telemetry
2025-03-06 00:34:46,653 INFO    MainThread:1541937 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-06 00:34:47,009 ERROR   MainThread:1541937 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/kanchan/Downloads/Courses/DL(DA6401)/CS23S025-Assignment-1_DA6401-DL/DLenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanchan/Downloads/Courses/DL(DA6401)/CS23S025-Assignment-1_DA6401-DL/DLenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
